"""social proof counters

Revision ID: fb6fb9e8211e
Revises: 93a5abcc97ec
Create Date: 2026-09-05 11:56:46.985648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6fb9e8211e'
down_revision: Union[str, Sequence[str], None] = '93a5abcc97ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_events', sa.Column('ref_user_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('save_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('projects', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_projects_save_count'), 'projects', ['save_count'], unique=False)
    op.create_index(op.f('ix_projects_view_count'), 'projects', ['view_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_view_count'), table_name='projects')
    op.drop_index(op.f('ix_projects_save_count'), table_name='projects')
    op.drop_column('projects', 'view_count')
    op.drop_column('projects', 'save_count')
    op.drop_column('analytics_events', 'ref_user_id')
    # ### end Alembic commands ###
